# Generated by Django 3.0 on 2020-01-25 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='Photos/Admins/%Y')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='Photos/Admins/%Y')),
                ('name', models.CharField(blank=True, max_length=50000)),
                ('role', models.CharField(blank=True, max_length=500000)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('facebook', models.CharField(blank=True, max_length=50000)),
                ('twitter', models.CharField(blank=True, max_length=50000)),
                ('instagram', models.CharField(blank=True, max_length=50000)),
                ('google_plus', models.CharField(blank=True, max_length=50000)),
                ('linkedin', models.CharField(blank=True, max_length=50000)),
            ],
        ),
    ]
