experience_choices = {
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9': 9,
    '10':10 
}

job_title_choices = {
    'Account & Finance': 'Account & Finance',
    'Information & Technology': 'Information & Technology',
    'Marketing': 'Marketing',
    'Real Estate Agent': 'Real Estate Agent',
    'Real Estate Broker': 'Real Estate Broker',
    'Associate brokers': 'Associate brokers',
    'REALTOR':'REALTOR',
    'Real estate clerks': 'Real estate clerks',
    'Office managers':'Office managers',
    'Inspectors': 'Inspectors',
    'Real estate managers': 'Real estate managers',
    'Real estate appraisers': 'Real estate appraisers',
    'Loan Professional': 'Loan Professional',
    'Loan underwriters':'Loan underwriters',
    'Licensed closing agents': 'Licensed closing agents',
    'Real Estate Consultant': 'Real Estate Consultant',
    'Real estate lawyers': 'Real estate lawyers',
    'Foreclosure specialists': 'Foreclosure specialists' ,
    'Web Developer' : 'Web Developer',    
    'Teacher': 'Teacher',
    'Instructor': 'Instructor',
    'Nurse':'Nurse',
    'Medical Personel': 'Medical Personel',
    'Computer Programmer': 'Computer Programmer',
    'Web Administrator': 'Web Administrator',
    'Data Base Manager': 'Data Base Manager',
    'Financial Assistant': 'Financial Assistant'
}
