# Generated by Django 2.2.6 on 2019-10-03 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(blank=True, max_length=50000)),
                ('phone', models.CharField(blank=True, max_length=50000)),
                ('service_1', models.CharField(blank=True, max_length=500000)),
                ('description_1', models.TextField(blank=True)),
                ('service_2', models.CharField(blank=True, max_length=500000)),
                ('description_2', models.TextField(blank=True)),
                ('service_3', models.CharField(blank=True, max_length=500000)),
                ('description_3', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
