# Generated by Django 2.2.6 on 2019-10-20 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50000)),
                ('sub_title', models.CharField(blank=True, max_length=50000)),
                ('photo', models.FileField(blank=True, upload_to='photos/blog/%Y/%m')),
                ('author_name', models.CharField(blank=True, max_length=50000)),
                ('category', models.CharField(blank=True, max_length=50000)),
                ('introduction', models.TextField(blank=True)),
                ('description1', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('description3', models.TextField(blank=True)),
                ('facebook', models.CharField(blank=True, max_length=50000)),
                ('twitter', models.CharField(blank=True, max_length=50000)),
                ('instagram', models.CharField(blank=True, max_length=50000)),
                ('google_plus', models.CharField(blank=True, max_length=50000)),
                ('linkedin', models.CharField(blank=True, max_length=50000)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=50000)),
                ('email', models.EmailField(blank=True, max_length=5000)),
                ('website', models.CharField(blank=True, max_length=5000)),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
