# Generated by Django 3.0 on 2020-01-25 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50000)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sub_title', models.CharField(blank=True, max_length=50000)),
                ('photo', models.FileField(blank=True, upload_to='Photos/Blog/%Y/%m')),
                ('category', models.CharField(blank=True, max_length=50000)),
                ('content', models.TextField(blank=True)),
                ('facebook', models.CharField(blank=True, max_length=50000)),
                ('twitter', models.CharField(blank=True, max_length=50000)),
                ('instagram', models.CharField(blank=True, max_length=50000)),
                ('google_plus', models.CharField(blank=True, max_length=50000)),
                ('linkedin', models.CharField(blank=True, max_length=50000)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50000)),
                ('email', models.EmailField(blank=True, max_length=5000)),
                ('website', models.CharField(blank=True, max_length=5000)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.Blog')),
            ],
            options={
                'ordering': ['comment_date'],
            },
        ),
    ]
