# Generated by Django 2.2.6 on 2019-10-09 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50000)),
                ('sub_title', models.CharField(blank=True, max_length=50000)),
                ('photo', models.FileField(blank=True, upload_to='photos/blog/%Y/%m')),
                ('author_name', models.CharField(blank=True, max_length=50000)),
                ('category', models.CharField(blank=True, max_length=50000)),
                ('introduction', models.TextField(blank=True)),
                ('description1', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('description3', models.TextField(blank=True)),
                ('facebook', models.CharField(blank=True, max_length=50000)),
                ('twitter', models.CharField(blank=True, max_length=50000)),
                ('instagram', models.CharField(blank=True, max_length=50000)),
                ('pinterest', models.CharField(blank=True, max_length=50000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/blog/comments/%Y')),
                ('user_name', models.CharField(blank=True, max_length=50000)),
                ('comment', models.TextField(blank=True)),
                ('comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
