# Generated by Django 2.2.6 on 2019-10-09 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=50)),
                ('description1', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(blank=True, max_length=5000)),
                ('status', models.CharField(blank=True, max_length=5000)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=5)),
                ('garage', models.IntegerField(blank=True, default=0)),
                ('area', models.CharField(blank=True, max_length=50000)),
                ('amenity1', models.CharField(blank=True, max_length=5000)),
                ('amenity2', models.CharField(blank=True, max_length=5000)),
                ('amenity3', models.CharField(blank=True, max_length=5000)),
                ('amenity4', models.CharField(blank=True, max_length=5000)),
                ('amenity5', models.CharField(blank=True, max_length=5000)),
                ('amenity6', models.CharField(blank=True, max_length=5000)),
                ('amenity7', models.CharField(blank=True, max_length=5000)),
                ('amenity8', models.CharField(blank=True, max_length=5000)),
                ('amenity9', models.CharField(blank=True, max_length=5000)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/properties/%Y/%m')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/properties/%Y/%m')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/properties/%Y/%m')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/properties/%Y/%m')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/properties/%Y/%m')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/properties/%Y/%m')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/properties/%Y/%m')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agents.Agent')),
            ],
        ),
    ]
