# Generated by Django 2.2.6 on 2019-10-22 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.FileField(upload_to='photos/Applications/Files/%Y')),
                ('name', models.CharField(blank=True, max_length=500000)),
                ('email', models.EmailField(blank=True, max_length=50000)),
                ('phone', models.CharField(blank=True, max_length=50000)),
                ('place_of_origin', models.CharField(max_length=5000)),
                ('current_city', models.CharField(max_length=5000)),
                ('neighbour_hood', models.CharField(max_length=5000)),
                ('current_employment', models.CharField(max_length=50000)),
                ('user_id', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=50000)),
                ('message', models.TextField(blank=True, max_length=50000)),
                ('application_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photos/Company Logo/%Y/%m')),
                ('company', models.CharField(blank=True, max_length=2000)),
                ('job_title', models.CharField(blank=True, max_length=2000)),
                ('job_available', models.BooleanField(blank=True, default=True)),
                ('address', models.CharField(blank=True, max_length=2000)),
                ('website', models.CharField(blank=True, max_length=2000)),
                ('employer', models.CharField(blank=True, max_length=2000)),
                ('mail', models.CharField(blank=True, max_length=2000)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('about_job', models.TextField(blank=True)),
                ('salary', models.IntegerField(blank=True)),
                ('experience', models.IntegerField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('responsibility_intro', models.TextField(blank=True)),
                ('responsibility1', models.CharField(blank=True, max_length=5000000)),
                ('responsibility2', models.CharField(blank=True, max_length=5000000)),
                ('responsibility3', models.CharField(blank=True, max_length=5000000)),
                ('responsibility4', models.CharField(blank=True, max_length=5000000)),
                ('responsibility5', models.CharField(blank=True, max_length=5000000)),
                ('responsibility6', models.CharField(blank=True, max_length=5000000)),
                ('responsibility7', models.CharField(blank=True, max_length=5000000)),
                ('responsibility8', models.CharField(blank=True, max_length=5000000)),
                ('responsibility9', models.CharField(blank=True, max_length=5000000)),
                ('responsibility10', models.CharField(blank=True, max_length=5000000)),
                ('qualification_intro', models.TextField(blank=True)),
                ('qualification1', models.CharField(blank=True, max_length=5000000)),
                ('qualification2', models.CharField(blank=True, max_length=5000000)),
                ('qualification3', models.CharField(blank=True, max_length=5000000)),
                ('qualification4', models.CharField(blank=True, max_length=5000000)),
                ('qualification5', models.CharField(blank=True, max_length=5000000)),
                ('qualification6', models.CharField(blank=True, max_length=5000000)),
                ('qualification7', models.CharField(blank=True, max_length=5000000)),
                ('qualification8', models.CharField(blank=True, max_length=5000000)),
                ('qualification9', models.CharField(blank=True, max_length=5000000)),
                ('qualification10', models.CharField(blank=True, max_length=5000000)),
                ('facebook', models.CharField(blank=True, max_length=50000)),
                ('google_plus', models.CharField(blank=True, max_length=50000)),
                ('twitter', models.CharField(blank=True, max_length=50000)),
                ('linked_in', models.CharField(blank=True, max_length=50000)),
                ('instagram', models.CharField(blank=True, max_length=50000)),
            ],
        ),
    ]
