# Generated by Django 2.2.6 on 2019-10-03 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30000)),
                ('name', models.CharField(max_length=30000)),
                ('photo_1', models.ImageField(upload_to='about/%Y/%m/%d/')),
                ('photo_2', models.ImageField(upload_to='about/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
